### ISSUE TITLE
Refactor image reader into own util module

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/Reaper#27]
Move the image reader to its own module so that it can also be reused by the sentiment analyser by OCRing image content.

**Comment by Bobbyperson** [comment]
OCR + sentiment analysis seems a bit overkill or otherwise not worth the effort IMO. Briefly scrolling through Northstar general all I see are either memes, cats, reaction gifs, or a random screenshot. Maybe like 1/20 images actually pertained to the current convo's sentiment but at the same time had no text. I feel like this would only make the sentiment analysis drop in quality.

**Comment by GeckoEidechse** [comment]
Fair point. I would still like to test it just to see whether it does make a difference. Either way we probably still wanna refactor the image reader into its own module just so that we can modularise the codebase a bit more and more easily re-use it in other parts of the code if need be ^^

**Comment by Bobbyperson** [comment]
Hey I'm a bit confused on what part of the code specifically needs to be made it's own module, or otherwise what functionality there is to be reused that isn't just a library. Could you please shed some light on this?

**Comment by GeckoEidechse** [comment]
Honestly at this point I'm not sure anymore if this is even needed. Basically I was thinking of just having a helper function to input an image into and get the OCR out of it again. But that's more or less what the current logic already does so I'm gonna just close this issue for now, as there's not really a point of doing it ^^"
